In this project, I want to create a regression model, that can evaluate, the amount of CO2 that comes out of the engine of a car.

lets import our libraries

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

now,lets read our data from a csv file

In [24]:
data = pd.read_csv("../dataset/FuelConsumption.csv")

In [25]:
data

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [26]:
data.head(n=10)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,2014,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,2014,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,2014,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,2014,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,2014,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212

In [27]:
data.tail()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [28]:
data.shape

(1067, 13)

In [29]:
data.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS'],
      dtype='object')

In [30]:
type(data)

pandas.core.frame.DataFrame

In [31]:
train,test = train_test_split(data , random_state=0)

In [32]:
x_train = train.drop(columns="CO2EMISSIONS")

In [33]:
y_train = train["CO2EMISSIONS"]

In [35]:
x_train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,12.1,8.7,10.6,27
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,11.8,8.8,10.5,27
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,9.4,7.5,8.5,33
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,10.5,7.2,9.0,31
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,9.9,8.3,9.2,31
...,...,...,...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,7.9,5.6,6.9,41
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,17.8,13.8,16.0,18
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,13.5,9.6,11.7,24
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.8,10.2,13.3,21
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,13.1,9.3,11.4,25

In [36]:
y_train

667     244
37      242
978     196
158     207
40      212
       ...
1033    186
763     256
835     269
559     306
684     262
Name: CO2EMISSIONS, Length: 800, dtype: int64

In [37]:
x_train["fuel_consumption"] =  x_train["FUELCONSUMPTION_CITY"]+x_train["FUELCONSUMPTION_COMB"]+x_train["FUELCONSUMPTION_COMB_MPG"]+x_train["FUELCONSUMPTION_HWY"]

In [38]:

x_train["fuel_consumption"] = (x_train["fuel_consumption"]/4)

In [39]:
x_train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,fuel_consumption
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,12.1,8.7,10.6,27,14.600
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,11.8,8.8,10.5,27,14.525
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,9.4,7.5,8.5,33,14.600
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,10.5,7.2,9.0,31,14.425
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,9.9,8.3,9.2,31,14.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,7.9,5.6,6.9,41,15.350
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,17.8,13.8,16.0,18,16.400
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,13.5,9.6,11.7,24,14.700
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.8,10.2,13.3,21,15.075
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,13.1,9.3,11.4,25,14.700

In [40]:
x_train = x_train.drop(columns=["FUELCONSUMPTION_CITY","FUELCONSUMPTION_COMB","FUELCONSUMPTION_COMB_MPG","FUELCONSUMPTION_HWY"])

In [41]:
x_train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,fuel_consumption
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,14.600
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,14.525
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,14.600
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,14.425
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,14.600
...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,15.350
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,16.400
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,14.700
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.075
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,14.700

at first, i just consider features,that i think are important,as i am interested in cars :))

In [42]:
y_train  =train["CO2EMISSIONS"]

In [47]:
type(y_train)

pandas.core.series.Series

(1067, 9)

i think for some features,we should use one hot encoding tecniques

In [17]:
from sklearn.preprocessing import OneHotEncoder