In this project, I want to create a regression model, that can evaluate, the amount of CO2 that comes out of the engine of a car.

lets import our libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

now,lets read our data from a csv file

In [3]:
data = pd.read_csv("../dataset/FuelConsumption.csv")

In [4]:
data

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [5]:
data.head(n=10)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
5,2014,ACURA,RLX,MID-SIZE,3.5,6,AS6,Z,11.9,7.7,10.0,28,230
6,2014,ACURA,TL,MID-SIZE,3.5,6,AS6,Z,11.8,8.1,10.1,28,232
7,2014,ACURA,TL AWD,MID-SIZE,3.7,6,AS6,Z,12.8,9.0,11.1,25,255
8,2014,ACURA,TL AWD,MID-SIZE,3.7,6,M6,Z,13.4,9.5,11.6,24,267
9,2014,ACURA,TSX,COMPACT,2.4,4,AS5,Z,10.6,7.5,9.2,31,212

In [6]:
data.tail()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [7]:
data.shape

(1067, 13)

In [8]:
data.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS'],
      dtype='object')

In [9]:
type(data)

pandas.core.frame.DataFrame

In [10]:
train,test = train_test_split(data , random_state=0)

In [11]:
x_train = train.drop(columns="CO2EMISSIONS")

In [12]:
y_train = train["CO2EMISSIONS"]

In [13]:
x_train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,12.1,8.7,10.6,27
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,11.8,8.8,10.5,27
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,9.4,7.5,8.5,33
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,10.5,7.2,9.0,31
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,9.9,8.3,9.2,31
...,...,...,...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,7.9,5.6,6.9,41
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,17.8,13.8,16.0,18
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,13.5,9.6,11.7,24
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.8,10.2,13.3,21
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,13.1,9.3,11.4,25

In [14]:
y_train

667     244
37      242
978     196
158     207
40      212
       ...
1033    186
763     256
835     269
559     306
684     262
Name: CO2EMISSIONS, Length: 800, dtype: int64

In [15]:
x_train["fuel_consumption"] =  x_train["FUELCONSUMPTION_CITY"]+x_train["FUELCONSUMPTION_COMB"]+x_train["FUELCONSUMPTION_COMB_MPG"]+x_train["FUELCONSUMPTION_HWY"]

In [16]:

x_train["fuel_consumption"] = (x_train["fuel_consumption"]/4)

In [17]:
x_train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,fuel_consumption
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,12.1,8.7,10.6,27,14.600
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,11.8,8.8,10.5,27,14.525
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,9.4,7.5,8.5,33,14.600
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,10.5,7.2,9.0,31,14.425
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,9.9,8.3,9.2,31,14.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,7.9,5.6,6.9,41,15.350
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,17.8,13.8,16.0,18,16.400
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,13.5,9.6,11.7,24,14.700
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.8,10.2,13.3,21,15.075
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,13.1,9.3,11.4,25,14.700

In [18]:
x_train = x_train.drop(columns=["FUELCONSUMPTION_CITY","FUELCONSUMPTION_COMB","FUELCONSUMPTION_COMB_MPG","FUELCONSUMPTION_HWY"])

In [19]:
x_train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,fuel_consumption
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,14.600
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,14.525
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,14.600
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,14.425
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,14.600
...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,15.350
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,16.400
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,14.700
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.075
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,14.700

at first, i just consider features,that i think are important,as i am interested in cars :))

In [20]:
y_train  =train["CO2EMISSIONS"]

In [21]:
type(y_train)

pandas.core.series.Series

In [24]:
x_train.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'fuel_consumption'],
      dtype='object')

In [28]:
train_x = x_train[["ENGINESIZE","CYLINDERS","fuel_consumption"]]

In [29]:
train_x

      ENGINESIZE  CYLINDERS  fuel_consumption
667          3.5          6            14.600
37           2.0          4            14.525
978          1.8          4            14.600
158          2.5          4            14.425
40           2.0          4            14.600
...          ...        ...               ...
1033         2.0          4            15.350
763          3.5          6            16.400
835          3.7          6            14.700
559          5.0          8            15.075
684          3.7          6            14.700

[800 rows x 3 columns]

In [30]:
train_x.shape

(800, 3)

In [32]:
lr = LinearRegression()
lr.fit(train_x,y_train)

LinearRegression()

In [34]:
print("accuracy score is :{}".format(lr.score(train_x,y_train)))

from sklearn.metrics import r2_score

accuracy score is :0.796175872754612

In [35]:
x_test = test.drop(columns=["CO2EMISSIONS"])

In [36]:
x_test

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
766,2014,MERCEDES-BENZ,ML 63 AMG 4MATIC,SUV - STANDARD,5.5,8,AS7,Z,17.2,13.5,15.5,18
204,2014,CHEVROLET,EQUINOX,SUV - SMALL,2.4,4,A6,X,10.5,7.3,9.1,31
629,2014,KIA,SPORTAGE,SUV - SMALL,2.4,4,A6,X,11.4,8.3,10.0,28
897,2014,PORSCHE,CAYMAN,TWO-SEATER,2.7,6,AM7,Z,10.7,7.4,9.2,31
711,2014,MAZDA,MAZDA3 5-DOOR (i-ELOOP),MID-SIZE,2.5,4,AS6,X,8.2,6.1,7.3,39
...,...,...,...,...,...,...,...,...,...,...,...,...
511,2014,HYUNDAI,SANTA FE SPORT 4WD,SUV - SMALL,2.0,4,A6,X,12.9,9.7,11.5,25
1021,2014,VOLKSWAGEN,BEETLE CONVERTIBLE,SUBCOMPACT,2.0,4,A6,Z,10.3,8.1,9.3,30
362,2014,FORD,EXPEDITION 4X4 FFV,SUV - STANDARD,5.4,8,A6,E,24.5,18.0,21.6,13
963,2014,SUBARU,XV CROSSTREK AWD,SUV - SMALL,2.0,4,M5,X,10.2,8.0,9.2,31
113,2014,BMW,ACTIVEHYBRID 3,COMPACT,3.0,6,A8,Z,9.2,7.1,8.3,34

In [37]:
y_test = test["CO2EMISSIONS"]

In [38]:
y_test.shape

(267,)

In [39]:
x_test.shape

(267, 12)

In [40]:
x_test.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG'],
      dtype='object')

In [41]:
x_test["fuel_consumption"] = x_test['FUELCONSUMPTION_CITY']+x_test["FUELCONSUMPTION_HWY"]+x_test["FUELCONSUMPTION_COMB"]+x_test["FUELCONSUMPTION_COMB_MPG"]
x_test["fuel_consumption"] = x_test["fuel_consumption"]/4

In [42]:
x_test["fuel_consumption"]

766     16.050
204     14.475
629     14.425
897     14.575
711     15.150
         ...
511     14.775
1021    14.425
362     19.275
963     14.600
113     14.650
Name: fuel_consumption, Length: 267, dtype: float64

In [46]:
temp_x_test = x_test.drop(columns=["FUELCONSUMPTION_CITY","FUELCONSUMPTION_HWY","FUELCONSUMPTION_COMB","FUELCONSUMPTION_COMB_MPG"])

In [47]:
temp_x_test

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,fuel_consumption
766,2014,MERCEDES-BENZ,ML 63 AMG 4MATIC,SUV - STANDARD,5.5,8,AS7,Z,16.050
204,2014,CHEVROLET,EQUINOX,SUV - SMALL,2.4,4,A6,X,14.475
629,2014,KIA,SPORTAGE,SUV - SMALL,2.4,4,A6,X,14.425
897,2014,PORSCHE,CAYMAN,TWO-SEATER,2.7,6,AM7,Z,14.575
711,2014,MAZDA,MAZDA3 5-DOOR (i-ELOOP),MID-SIZE,2.5,4,AS6,X,15.150
...,...,...,...,...,...,...,...,...,...
511,2014,HYUNDAI,SANTA FE SPORT 4WD,SUV - SMALL,2.0,4,A6,X,14.775
1021,2014,VOLKSWAGEN,BEETLE CONVERTIBLE,SUBCOMPACT,2.0,4,A6,Z,14.425
362,2014,FORD,EXPEDITION 4X4 FFV,SUV - STANDARD,5.4,8,A6,E,19.275
963,2014,SUBARU,XV CROSSTREK AWD,SUV - SMALL,2.0,4,M5,X,14.600
113,2014,BMW,ACTIVEHYBRID 3,COMPACT,3.0,6,A8,Z,14.650

In [49]:
test_x = temp_x_test[["ENGINESIZE","CYLINDERS","fuel_consumption"]]

In [51]:
from sklearn.metrics import r2_score

In [52]:
predicted = lr.predict(test_x)

In [72]:
accuracy = r2_score(y_test,predicted)
print(accuracy)

0.7276711038738841

i am not sattisfied
lets work more

In [61]:
type(new_x_train)

numpy.ndarray

In [62]:
new_x_train = np.asanyarray(train["ENGINESIZE"])
new_y_train  = np.asanyarray(train["CO2EMISSIONS"])

new_x_train = new_x_train.reshape(-1,1)



linear_r = LinearRegression()
linear_r.fit(new_x_train,new_y_train)

LinearRegression()

In [68]:
new_x_test = np.asanyarray(test["ENGINESIZE"])
new_y_test = np.asanyarray(test["CO2EMISSIONS"])

new_x_test = new_x_test.reshape(-1,1)

predicted2  = linear_r.predict(new_x_test)

In [71]:
accu = r2_score(new_y_test,predicted)
print(accu)

0.7276711038738841

As we can see,it seems with simple linear regression,having the r2score of 72 percent,is like its maximum...now lets try encoding to see if we can improve the model's r2scre

In [73]:
from sklearn.preprocessing import OneHotEncoder

In [74]:
train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,11.8,8.8,10.5,27,242
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,9.4,7.5,8.5,33,196
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,10.5,7.2,9.0,31,207
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,9.9,8.3,9.2,31,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,7.9,5.6,6.9,41,186
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,17.8,13.8,16.0,18,256
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,13.5,9.6,11.7,24,269
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.8,10.2,13.3,21,306
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,13.1,9.3,11.4,25,262

In [75]:
test

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
766,2014,MERCEDES-BENZ,ML 63 AMG 4MATIC,SUV - STANDARD,5.5,8,AS7,Z,17.2,13.5,15.5,18,356
204,2014,CHEVROLET,EQUINOX,SUV - SMALL,2.4,4,A6,X,10.5,7.3,9.1,31,209
629,2014,KIA,SPORTAGE,SUV - SMALL,2.4,4,A6,X,11.4,8.3,10.0,28,230
897,2014,PORSCHE,CAYMAN,TWO-SEATER,2.7,6,AM7,Z,10.7,7.4,9.2,31,212
711,2014,MAZDA,MAZDA3 5-DOOR (i-ELOOP),MID-SIZE,2.5,4,AS6,X,8.2,6.1,7.3,39,168
...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,2014,HYUNDAI,SANTA FE SPORT 4WD,SUV - SMALL,2.0,4,A6,X,12.9,9.7,11.5,25,264
1021,2014,VOLKSWAGEN,BEETLE CONVERTIBLE,SUBCOMPACT,2.0,4,A6,Z,10.3,8.1,9.3,30,214
362,2014,FORD,EXPEDITION 4X4 FFV,SUV - STANDARD,5.4,8,A6,E,24.5,18.0,21.6,13,346
963,2014,SUBARU,XV CROSSTREK AWD,SUV - SMALL,2.0,4,M5,X,10.2,8.0,9.2,31,212
113,2014,BMW,ACTIVEHYBRID 3,COMPACT,3.0,6,A8,Z,9.2,7.1,8.3,34,191

In [83]:
train["fuel_con"] = train["FUELCONSUMPTION_CITY"]+train["FUELCONSUMPTION_COMB"]+train["FUELCONSUMPTION_COMB_MPG"]+train["FUELCONSUMPTION_HWY"]

train["fuel_con"]  = train["fuel_con"]*4

In [78]:
train = train.drop(columns=["FUELCONSUMPTION_CITY","FUELCONSUMPTION_COMB","FUELCONSUMPTION_COMB_MPG","FUELCONSUMPTION_HWY"])

In [86]:
train

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,CO2EMISSIONS,fuel_con
667,2014,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,244,14.600
37,2014,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,242,14.525
978,2014,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,196,14.600
158,2014,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,207,14.425
40,2014,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,212,14.600
...,...,...,...,...,...,...,...,...,...,...
1033,2014,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,186,15.350
763,2014,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,256,16.400
835,2014,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,269,14.700
559,2014,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,306,15.075
684,2014,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,262,14.700

In [84]:
test["fuel_con"] = test["FUELCONSUMPTION_CITY"]+test["FUELCONSUMPTION_COMB"]+test["FUELCONSUMPTION_COMB_MPG"]+test["FUELCONSUMPTION_HWY"]

test["fuel_con"]  = test["fuel_con"]/4

In [85]:
test

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,fuel_con
766,2014,MERCEDES-BENZ,ML 63 AMG 4MATIC,SUV - STANDARD,5.5,8,AS7,Z,17.2,13.5,15.5,18,356,16.050
204,2014,CHEVROLET,EQUINOX,SUV - SMALL,2.4,4,A6,X,10.5,7.3,9.1,31,209,14.475
629,2014,KIA,SPORTAGE,SUV - SMALL,2.4,4,A6,X,11.4,8.3,10.0,28,230,14.425
897,2014,PORSCHE,CAYMAN,TWO-SEATER,2.7,6,AM7,Z,10.7,7.4,9.2,31,212,14.575
711,2014,MAZDA,MAZDA3 5-DOOR (i-ELOOP),MID-SIZE,2.5,4,AS6,X,8.2,6.1,7.3,39,168,15.150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,2014,HYUNDAI,SANTA FE SPORT 4WD,SUV - SMALL,2.0,4,A6,X,12.9,9.7,11.5,25,264,14.775
1021,2014,VOLKSWAGEN,BEETLE CONVERTIBLE,SUBCOMPACT,2.0,4,A6,Z,10.3,8.1,9.3,30,214,14.425
362,2014,FORD,EXPEDITION 4X4 FFV,SUV - STANDARD,5.4,8,A6,E,24.5,18.0,21.6,13,346,19.275
963,2014,SUBARU,XV CROSSTREK AWD,SUV - SMALL,2.0,4,M5,X,10.2,8.0,9.2,31,212,14.600
113,2014,BMW,ACTIVEHYBRID 3,COMPACT,3.0,6,A8,Z,9.2,7.1,8.3,34,191,14.650

In [87]:
train_feat = train.drop(columns="CO2EMISSIONS")
train_target = train["CO2EMISSIONS"]

test_feat = test.drop(columns="CO2EMISSIONS")
test_target  = test["CO2EMISSIONS"]

In [88]:
train_feat.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'fuel_con'],
      dtype='object')

since all of the values of model column is 2014,it is not a necessary feature,so we will drop it in the next cell

In [89]:
train_feat = train_feat.drop(columns="MODELYEAR")

In [90]:
train_feat.columns

Index(['MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'fuel_con'],
      dtype='object')

In [91]:
train_feat

,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,fuel_con
667,LEXUS,IS 350 C,SUBCOMPACT,3.5,6,AS6,Z,14.600
37,AUDI,ALLROAD QUATTRO,STATION WAGON - SMALL,2.0,4,AS8,Z,14.525
978,TOYOTA,COROLLA MATRIX,STATION WAGON - SMALL,1.8,4,A4,X,14.600
158,CADILLAC,ATS,COMPACT,2.5,4,AS6,X,14.425
40,AUDI,Q5 HYBRID,SUV - SMALL,2.0,4,AS8,Z,14.600
...,...,...,...,...,...,...,...,...
1033,VOLKSWAGEN,GOLF WAGON TDI CLEAN DIESEL,STATION WAGON - SMALL,2.0,4,M6,D,15.350
763,MERCEDES-BENZ,ML 350 4MATIC FFV,SUV - STANDARD,3.5,6,AS7,E,16.400
835,NISSAN,370Z ROADSTER,TWO-SEATER,3.7,6,M6,Z,14.700
559,JAGUAR,XJL SUPERCHARGED,FULL-SIZE,5.0,8,AS8,Z,15.075
684,LINCOLN,MKZ AWD,MID-SIZE,3.7,6,AS6,X,14.700